// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVYdcTEnA3JKL03LoOgIjbPjm_Gippmxk',
    appId: '1:772250867140:android:77975346cd058ef7b78091',
    messagingSenderId: '772250867140',
    projectId: 'umivpn-staging',
    storageBucket: 'umivpn-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3BuG2IBl4PZnZY348_gDLvi_wpj66S4',
    appId: '1:772250867140:ios:fb9623cf74437dfcb78091',
    messagingSenderId: '772250867140',
    projectId: 'umivpn-staging',
    storageBucket: 'umivpn-staging.firebasestorage.app',
    iosBundleId: 'com.umivpn.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF3BuG2IBl4PZnZY348_gDLvi_wpj66S4',
    appId: '1:772250867140:ios:fb9623cf74437dfcb78091',
    messagingSenderId: '772250867140',
    projectId: 'umivpn-staging',
    storageBucket: 'umivpn-staging.firebasestorage.app',
    iosBundleId: 'com.umivpn.dev',
  );
}
