// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhTg1_VYYlTmC1AAVeizPYJf5LQHxnIA',
    appId: '1:44508252344:android:867c0bd2c5cd4cd2364c4d',
    messagingSenderId: '44508252344',
    projectId: 'umivpn',
    storageBucket: 'umivpn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFsIENEmO-fEgw-_KDf6qGfaQsBbFKU8',
    appId: '1:44508252344:ios:3c1553784d2b709f364c4d',
    messagingSenderId: '44508252344',
    projectId: 'umivpn',
    storageBucket: 'umivpn.firebasestorage.app',
    iosBundleId: 'com.5vnetwork.umi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFsIENEmO-fEgw-_KDf6qGfaQsBbFKU8',
    appId: '1:44508252344:ios:3c1553784d2b709f364c4d',
    messagingSenderId: '44508252344',
    projectId: 'umivpn',
    storageBucket: 'umivpn.firebasestorage.app',
    iosBundleId: 'com.5vnetwork.umi',
  );
}
